"""
Abstract base class for all AlphaHood strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any

@dataclass
class OptionDetails:
    """Details specific to options contracts."""
    contract_type: str  # "CALL" or "PUT"
    strike: float
    expiration: str  # YYYY-MM-DD
    greeks: Dict[str, float]

@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    direction: str  # "LONG" or "SHORT"
    strategy_name: str
    confidence: float  # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    order_type: str  # "MARKET" or "LIMIT"
    asset_type: str  # "EQUITY" or "OPTION"
    option_details: Optional[OptionDetails] = None

@dataclass
class ExitSignal:
    """Exit signal generated by a strategy."""
    symbol: str
    reason: str
    urgency: str  # "IMMEDIATE" or "NORMAL"

class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""
    
    @property
    def name(self) -> str:
        return self.__class__.__name__.replace("Strategy", "")

    @abstractmethod
    def generate_signals(self, symbols: list[str], market_data: Dict[str, Any]) -> list[Signal]:
        """
        Evaluate symbols against market data to generate entry signals.
        """
        pass

    @abstractmethod
    def should_exit(self, position: Any, market_data: Dict[str, Any]) -> Optional[ExitSignal]:
        """
        Evaluate an existing position to determine if it should be exited.
        """
        pass
